# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/anupam/Desktop/GITHUB/Minor-2nd-sem/desktop-app/outputwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OutputDialog(object):
    def setupUi(self, OutputDialog):
        OutputDialog.setObjectName("OutputDialog")
        OutputDialog.resize(951, 591)
        OutputDialog.setMinimumSize(QtCore.QSize(0, 0))
        OutputDialog.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        OutputDialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OutputDialog.setWindowIcon(icon)
        self.imgLabel = QtWidgets.QLabel(OutputDialog)
        self.imgLabel.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.imgLabel.setMinimumSize(QtCore.QSize(4, 0))
        self.imgLabel.setMaximumSize(QtCore.QSize(640, 480))
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(OutputDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 500, 651, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ClockInButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ClockInButton.setFont(font)
        self.ClockInButton.setCheckable(True)
        self.ClockInButton.setObjectName("ClockInButton")
        self.horizontalLayout.addWidget(self.ClockInButton)
        self.gridLayoutWidget = QtWidgets.QWidget(OutputDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(660, 10, 281, 75))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.Date_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Date_Label.setFont(font)
        self.Date_Label.setObjectName("Date_Label")
        self.gridLayout_2.addWidget(self.Date_Label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.Time_Label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Time_Label.setFont(font)
        self.Time_Label.setObjectName("Time_Label")
        self.gridLayout_2.addWidget(self.Time_Label, 1, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(OutputDialog)
        self.groupBox.setGeometry(QtCore.QRect(660, 110, 271, 271))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 127, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(120, 30, 131, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.NameLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.NameLabel.setFont(font)
        self.NameLabel.setText("")
        self.NameLabel.setObjectName("NameLabel")
        self.verticalLayout_2.addWidget(self.NameLabel)
        self.RollLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.RollLabel.setFont(font)
        self.RollLabel.setText("")
        self.RollLabel.setObjectName("RollLabel")
        self.verticalLayout_2.addWidget(self.RollLabel)
        self.StatusLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setText("")
        self.StatusLabel.setObjectName("StatusLabel")
        self.verticalLayout_2.addWidget(self.StatusLabel)
        self.Attendance = QtWidgets.QLabel(OutputDialog)
        self.Attendance.setGeometry(QtCore.QRect(700, 500, 212, 78))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Attendance.setFont(font)
        self.Attendance.setAutoFillBackground(False)
        self.Attendance.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.Attendance.setFrameShape(QtWidgets.QFrame.Box)
        self.Attendance.setWordWrap(False)
        self.Attendance.setOpenExternalLinks(True)
        self.Attendance.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.Attendance.setObjectName("Attendance")

        self.retranslateUi(OutputDialog)
        QtCore.QMetaObject.connectSlotsByName(OutputDialog)

    def retranslateUi(self, OutputDialog):
        _translate = QtCore.QCoreApplication.translate
        OutputDialog.setWindowTitle(_translate("OutputDialog", "Face Recognition Attendance App"))
        self.ClockInButton.setText(_translate("OutputDialog", "Check In"))
        self.label.setText(_translate("OutputDialog", "Date :"))
        self.Date_Label.setText(_translate("OutputDialog", "-"))
        self.label_2.setText(_translate("OutputDialog", "Time :"))
        self.Time_Label.setText(_translate("OutputDialog", "-"))
        self.groupBox.setTitle(_translate("OutputDialog", "Details"))
        self.label_3.setText(_translate("OutputDialog", "Name : "))
        self.label_5.setText(_translate("OutputDialog", "Roll no :"))
        self.label_4.setText(_translate("OutputDialog", "Status :"))
        self.Attendance.setText(_translate("OutputDialog", " Attendance Sheet"))

import resource_rc
